1. Archive exploration

**About the data**

This dataset includes information on [Water Conflict and Crisis Events in the Colorado River Basin](https://www.sciencebase.gov/catalog/item/63acac09d34e92aad3ca1480) and was sourced from the USGS digital repository [ScienceBase](https://www.sciencebase.gov/catalog/). These data were collected from 2005-01-01 to 2021-12-31, with the purpose of understanding vulnerability to water insecurity, resiliency demonstrated by institutions, and conflict or crisis around water resource management (Holloman et al., 2023).

**Resources**

Holloman, D.V., Hines, M.K., and Zoanni, D.K., 2023, Coded Water Conflict and Crisis Events in the Colorado River Basin, Derived from LexisNexis search 2005-2021: U.S. Geological Survey data release, [https://doi.org/10.5066/P9X6WR7J]().

**Date of Access**

2026-10-07

In [1]:
import pandas as pd
import numpy as np

In [4]:
# Load in the data
df = pd.read_csv('data/Colorado River Basin Water Conflict Table.csv')

(268, 48)

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,...,12,0,0,0,1,0,0,0,12,1

In [5]:
# Display the df with all columns
pd.set_option("display.max_columns", None)

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1

In [6]:
print(df.shape)
df.head(3)

(268, 48)

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Event                                         268 non-null    int64
 1   Search Source                                 268 non-null    str
 2   Newspaper                                     268 non-null    str
 3   Article Title                                 268 non-null    str
 4   Duplicate                                     267 non-null    object
 5   Report Date                                   267 non-null    str
 6   Report Year                                   265 non-null    float64
 7   Event Date                                    248 non-null    str
 8   Event Day                                     18 non-null     float64
 9   Event Month                                   212 non-null    float64
 10  Event Year                                    257 non-null    float64
 11  Conflict Present                              252 non-null    str
 12  Crisis Present                                254 non-null    str
 13  Basin                                         250 non-null    str
 14  HUC6                                          110 non-null    str
 15  HUC2                                          250 non-null    str
 16  Place                                         254 non-null    str
 17  County                                        8 non-null      str
 18  County FIPS                                   8 non-null      float64
 19  State                                         178 non-null    str
 20  State FIPS                                    178 non-null    str
 21  Urban or Rural                                254 non-null    str
 22  Issue Type                                    255 non-null    str
 23  Event Summary                                 256 non-null    str
 24  Stakeholders                                  255 non-null    str
 25  Intensity Value                               255 non-null    float64
 26  Comments                                      190 non-null    str
 27  Related Observation Themes                    86 non-null     str
 28  Article Text Search - water quality           268 non-null    int64
 29  Article Text Search - invasive species        268 non-null    int64
 30  Article Text Search - conservation            268 non-null    int64
 31  Article Text Search - drought                 268 non-null    int64
 32  Article Text Search - flood                   268 non-null    int64
 33  Article Text Search - ground water depletion  268 non-null    int64
 34  Article Text Search - depletion               268 non-null    int64
 35  Article Text Search - infrastructure          268 non-null    int64
 36  Article Text Search - fish passage            268 non-null    int64
 37  Article Text Search - instream water rights   268 non-null    int64
 38  Article Text Search - water rights            268 non-null    int64
 39  Article Text Search - intergovernmental       268 non-null    int64
 40  Article Text Search - water transfers         268 non-null    int64
 41  Article Text Search - navigation              268 non-null    int64
 42  Article Text Search - fish                    268 non-null    int64
 43  Article Text Search - invasive                268 non-null    int64
 44  Article Text Search - diversion               268 non-null    int64
 45  Article Text Search - water diversion         268 non-null    int64
 46  Article Text Search - instream                268 non-null    int64
 47  Article Text Search - aquatic                 268 non-null    int64
dtypes: float64(6), int64(21), object(1), str(20)
memory usage: 100.6+ KB

In [8]:
df.nunique()

Event                                           268
Search Source                                     6
Newspaper                                        45
Article Title                                   267
Duplicate                                         2
Report Date                                     235
Report Year                                      18
Event Date                                       52
Event Day                                        12
Event Month                                      12
Event Year                                       21
Conflict Present                                  2
Crisis Present                                    2
Basin                                            25
HUC6                                             22
HUC2                                              7
Place                                           135
County                                            3
County FIPS                                       3
State                                            23
State FIPS                                       19
Urban or Rural                                    6
Issue Type                                       19
Event Summary                                   253
Stakeholders                                    199
Intensity Value                                  10
Comments                                        184
Related Observation Themes                       21
Article Text Search - water quality              10
Article Text Search - invasive species            2
Article Text Search - conservation               15
Article Text Search - drought                    19
Article Text Search - flood                      10
Article Text Search - ground water depletion      1
Article Text Search - depletion                   2
Article Text Search - infrastructure              9
Article Text Search - fish passage                1
Article Text Search - instream water rights       1
Article Text Search - water rights               17
Article Text Search - intergovernmental           2
Article Text Search - water transfers             2
Article Text Search - navigation                  2
Article Text Search - fish                        8
Article Text Search - invasive                    3
Article Text Search - diversion                   6
Article Text Search - water diversion             2
Article Text Search - instream                    5
Article Text Search - aquatic                     5
dtype: int64