1. Archive exploration

**About the data**

This dataset includes information on [Water Conflict and Crisis Events in the Colorado River Basin](https://www.sciencebase.gov/catalog/item/63acac09d34e92aad3ca1480) and was sourced from the USGS digital repository [ScienceBase](https://www.sciencebase.gov/catalog/). These data were collected from 2005-01-01 to 2021-12-31, with the purpose of understanding vulnerability to water insecurity, resiliency demonstrated by institutions, and conflict or crisis around water resource management (Holloman et al., 2023).

**Resources**

Holloman, D.V., Hines, M.K., and Zoanni, D.K., 2023, Coded Water Conflict and Crisis Events in the Colorado River Basin, Derived from LexisNexis search 2005-2021: U.S. Geological Survey data release, [https://doi.org/10.5066/P9X6WR7J]().

**Date of Access**

2026-10-07

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load in the data
df = pd.read_csv('data/Colorado River Basin Water Conflict Table.csv')

In [3]:
# Display the df with all columns
pd.set_option("display.max_columns", None)

In [4]:
print(df.shape)
df.head(3)

(268, 48)

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Event                                         268 non-null    int64
 1   Search Source                                 268 non-null    str
 2   Newspaper                                     268 non-null    str
 3   Article Title                                 268 non-null    str
 4   Duplicate                                     267 non-null    object
 5   Report Date                                   267 non-null    str
 6   Report Year                                   265 non-null    float64
 7   Event Date                                    248 non-null    str
 8   Event Day                                     18 non-null     float64
 9   Event Month                                   212 non-null    float64
 10  Event Year                                    257 non-null    float64
 11  Conflict Present                              252 non-null    str
 12  Crisis Present                                254 non-null    str
 13  Basin                                         250 non-null    str
 14  HUC6                                          110 non-null    str
 15  HUC2                                          250 non-null    str
 16  Place                                         254 non-null    str
 17  County                                        8 non-null      str
 18  County FIPS                                   8 non-null      float64
 19  State                                         178 non-null    str
 20  State FIPS                                    178 non-null    str
 21  Urban or Rural                                254 non-null    str
 22  Issue Type                                    255 non-null    str
 23  Event Summary                                 256 non-null    str
 24  Stakeholders                                  255 non-null    str
 25  Intensity Value                               255 non-null    float64
 26  Comments                                      190 non-null    str
 27  Related Observation Themes                    86 non-null     str
 28  Article Text Search - water quality           268 non-null    int64
 29  Article Text Search - invasive species        268 non-null    int64
 30  Article Text Search - conservation            268 non-null    int64
 31  Article Text Search - drought                 268 non-null    int64
 32  Article Text Search - flood                   268 non-null    int64
 33  Article Text Search - ground water depletion  268 non-null    int64
 34  Article Text Search - depletion               268 non-null    int64
 35  Article Text Search - infrastructure          268 non-null    int64
 36  Article Text Search - fish passage            268 non-null    int64
 37  Article Text Search - instream water rights   268 non-null    int64
 38  Article Text Search - water rights            268 non-null    int64
 39  Article Text Search - intergovernmental       268 non-null    int64
 40  Article Text Search - water transfers         268 non-null    int64
 41  Article Text Search - navigation              268 non-null    int64
 42  Article Text Search - fish                    268 non-null    int64
 43  Article Text Search - invasive                268 non-null    int64
 44  Article Text Search - diversion               268 non-null    int64
 45  Article Text Search - water diversion         268 non-null    int64
 46  Article Text Search - instream                268 non-null    int64
 47  Article Text Search - aquatic                 268 non-null    int64
dtypes: float64(6), int64(21), object(1), str(20)
memory usage: 100.6+ KB

In [6]:
df.nunique()

Event                                           268
Search Source                                     6
Newspaper                                        45
Article Title                                   267
Duplicate                                         2
Report Date                                     235
Report Year                                      18
Event Date                                       52
Event Day                                        12
Event Month                                      12
Event Year                                       21
Conflict Present                                  2
Crisis Present                                    2
Basin                                            25
HUC6                                             22
HUC2                                              7
Place                                           135
County                                            3
County FIPS                                       3
State                                            23
State FIPS                                       19
Urban or Rural                                    6
Issue Type                                       19
Event Summary                                   253
Stakeholders                                    199
Intensity Value                                  10
Comments                                        184
Related Observation Themes                       21
Article Text Search - water quality              10
Article Text Search - invasive species            2
Article Text Search - conservation               15
Article Text Search - drought                    19
Article Text Search - flood                      10
Article Text Search - ground water depletion      1
Article Text Search - depletion                   2
Article Text Search - infrastructure              9
Article Text Search - fish passage                1
Article Text Search - instream water rights       1
Article Text Search - water rights               17
Article Text Search - intergovernmental           2
Article Text Search - water transfers             2
Article Text Search - navigation                  2
Article Text Search - fish                        8
Article Text Search - invasive                    3
Article Text Search - diversion                   6
Article Text Search - water diversion             2
Article Text Search - instream                    5
Article Text Search - aquatic                     5
dtype: int64

In [7]:
df.describe()

,Event,Report Year,Event Day,Event Month,Event Year,County FIPS,Intensity Value,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
count,268.000000,265.000000,18.000000,212.000000,257.000000,8.000000,255.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.0,268.000000,268.000000,268.0,268.0,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
mean,134.500000,2017.449057,18.444444,6.259434,2016.591440,11170.500000,0.219608,0.671642,0.014925,2.007463,4.600746,0.432836,0.0,0.011194,0.555970,0.0,0.0,3.134328,0.003731,0.022388,0.007463,0.410448,0.033582,0.182836,0.011194,0.089552,0.093284
std,77.509139,4.314160,6.887518,3.679539,10.346365,15437.657326,1.995765,1.472729,0.121481,2.633681,4.006680,2.418554,0.0,0.105405,1.281035,0.0,0.0,3.456072,0.061085,0.148219,0.086225,1.109798,0.200166,0.734493,0.105405,0.860822,0.632064
min,1.000000,2005.000000,4.000000,1.000000,1900.000000,4027.000000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,67.750000,2015.000000,13.250000,3.000000,2015.000000,4027.000000,-1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,134.500000,2019.000000,19.000000,5.000000,2019.000000,6047.000000,0.000000,0.000000,0.000000,1.000000,4.500000,0.000000,0.0,0.000000,0.000000,0.0,0.0,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,201.250000,2021.000000,20.000000,9.000000,2021.000000,8067.000000,1.500000,1.000000,0.000000,3.000000,7.000000,0.000000,0.0,0.000000,1.000000,0.0,0.0,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,268.000000,2022.000000,31.000000,12.000000,2023.000000,49055.000000,5.000000,10.000000,1.000000,15.000000,26.000000,31.000000,0.0,1.000000,9.000000,0.0,0.0,18.000000,1.000000,1.000000,1.000000,8.000000,2.000000,7.000000,1.000000,12.000000,9.000000

In [9]:
df.isna().sum()

Event                                             0
Search Source                                     0
Newspaper                                         0
Article Title                                     0
Duplicate                                         1
Report Date                                       1
Report Year                                       3
Event Date                                       20
Event Day                                       250
Event Month                                      56
Event Year                                       11
Conflict Present                                 16
Crisis Present                                   14
Basin                                            18
HUC6                                            158
HUC2                                             18
Place                                            14
County                                          260
County FIPS                                     260
State                                            90
State FIPS                                       90
Urban or Rural                                   14
Issue Type                                       13
Event Summary                                    12
Stakeholders                                     13
Intensity Value                                  13
Comments                                         78
Related Observation Themes                      182
Article Text Search - water quality               0
Article Text Search - invasive species            0
Article Text Search - conservation                0
Article Text Search - drought                     0
Article Text Search - flood                       0
Article Text Search - ground water depletion      0
Article Text Search - depletion                   0
Article Text Search - infrastructure              0
Article Text Search - fish passage                0
Article Text Search - instream water rights       0
Article Text Search - water rights                0
Article Text Search - intergovernmental           0
Article Text Search - water transfers             0
Article Text Search - navigation                  0
Article Text Search - fish                        0
Article Text Search - invasive                    0
Article Text Search - diversion                   0
Article Text Search - water diversion             0
Article Text Search - instream                    0
Article Text Search - aquatic                     0
dtype: int64

In [10]:
df['Issue Type'].value_counts()

Issue Type
Drought                                                                       66
Water rights more generally                                                   51
Intergovernmental issues                                                      43
Conservation                                                                  43
Infrastructure issues                                                         15
Water quality                                                                 10
Instream water rights                                                          6
Water transfers                                                                6
Flood                                                                          4
Intergovernmental issues: Water rights more generally                          2
Intergovernmental issues: Drought                                              1
Intergovernmental issues: Water transfers                                      1
Intergovernmental issues: Conservation                                         1
Conservation; Drought                                                          1
Fish passage                                                                   1
Ground water depletion                                                         1
Conservation; Water rights more generally                                      1
Drought; Water quality; Water rights more generally; Infrastructure issues     1
Conservation; Ground water depletion                                           1
Name: count, dtype: int64

In [17]:
print(df['Place'].nunique())
df['Place'].value_counts()

135

Place
Entire Colorado River Basin              19
State of Arizona                         17
Colorado River Basin                     13
Great Salt Lake                          10
Phoenix, AZ                               6
                                         ..
Grand Valley, CO                          1
Austin, TX                                1
Tempe, AZ                                 1
Yuma, AZ                                  1
State of Arizona, State of California     1
Name: count, Length: 135, dtype: int64

In [18]:
print(df['State'].nunique())
df['State'].value_counts()

23

State
AZ                            66
CO                            34
UT                            27
NV                            10
CA                             7
NM                             6
AZ; CA                         4
AZ; UT                         3
AZ; CA; CO; NV; NM; UT; WY     3
AZ; NV                         2
CO; UT; WY; NM                 2
NV; AZ                         2
CO; AZ                         2
OH; UT                         1
AZ; CO; NM; UT                 1
UT; AZ                         1
CO; WY                         1
AZ; CA; NV                     1
UT; CO; WY                     1
CA; NV; AZ                     1
AZ; NM                         1
WY; UT; CO                     1
TX                             1
Name: count, dtype: int64

In [19]:
print(df['Conflict Present'].nunique())
df['Conflict Present'].value_counts()

2

Conflict Present
Y    145
N    107
Name: count, dtype: int64

### String accessor for pandas.Series

In [20]:
# Example series
s = pd.Series(['California; Nevada', 'Arizona', np.nan, 'Nevada; Utah'])
s

0    California; Nevada
1               Arizona
2                   NaN
3          Nevada; Utah
dtype: str

In [21]:
# Use str accessor with additional methods to perform string operations

s.str.split(';') # Created list of of individual strings distinguished by where ; used to be, but still in same row

0    [California,  Nevada]
1                [Arizona]
2                      NaN
3          [Nevada,  Utah]
dtype: object

In [22]:
s.str.split(';').explode() # Seperates individual strings in list. Preserves index, so there are duplicates

0    California
0        Nevada
1       Arizona
2           NaN
3        Nevada
3          Utah
dtype: str

### Examine state codes

In [26]:
# Which states have non NA values
df.loc[df['State'].notna(), 'State']

0          CO
1          CO
2          UT
5          AZ
11     OH; UT
        ...
263        CO
264        CO
265    AZ; CA
266        AZ
267        AZ
Name: State, Length: 178, dtype: str

### Exploratory wrangling

In [28]:
df.columns

Index(['Event', 'Search Source', 'Newspaper', 'Article Title', 'Duplicate',
       'Report Date', 'Report Year', 'Event Date', 'Event Day', 'Event Month',
       'Event Year', 'Conflict Present', 'Crisis Present', 'Basin', 'HUC6',
       'HUC2', 'Place', 'County', 'County FIPS', 'State', 'State FIPS',
       'Urban or Rural', 'Issue Type', 'Event Summary', 'Stakeholders',
       'Intensity Value', 'Comments', 'Related Observation Themes',
       'Article Text Search - water quality',
       'Article Text Search - invasive species',
       'Article Text Search - conservation', 'Article Text Search - drought',
       'Article Text Search - flood',
       'Article Text Search - ground water depletion',
       'Article Text Search - depletion',
       'Article Text Search - infrastructure',
       'Article Text Search - fish passage',
       'Article Text Search - instream water rights',
       'Article Text Search - water rights',
       'Article Text Search - intergovernmental',
       'Article Text Search - water transfers',
       'Article Text Search - navigation', 'Article Text Search - fish',
       'Article Text Search - invasive', 'Article Text Search - diversion',
       'Article Text Search - water diversion',
       'Article Text Search - instream', 'Article Text Search - aquatic'],
      dtype='str')

select the State column and the rows corresponding to water conflicts occurring
split the strings in the column by the delimiter ;
explode the resulting pandas.Series to have each element of a list as a separate row
find the unique string values in the resulting pandas.Series, keeping the NAs

In [31]:
df.loc[df['Conflict Present']=='Y','State'].str.split(';').explode().unique()

<StringArray>
[ 'CO',   nan,  'AZ',  'OH', ' UT',  'UT',  'CA', ' NV', ' WY', ' NM', ' CA',
  'NV', ' AZ', ' CO',  'NM',  'WY']
Length: 16, dtype: str